# Generated by Django 3.1.7 on 2021-02-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voteos',
            new_name='votes',
        ),
    ]
